title: Letters On Liquors
description: "The blog that looks into typography on beverages. "
header_text: "Letters On Liquors "
footer_text: Copyright 2020 Lily-Rose Hill
header_feature_image: ../uploads/img_0112.jpg
bannerheight: 40vmax
logo: ../uploads/img_0108.jpg
favicon: ../uploads/img_0108.jpg
gridlayout: true
fixednavbar: false
upzoom: true
items:
  - name: About The Author
    siteurl: /aboutme
