title: Letters On Liquors
description: "The blog that looks into typography on beverages. "
header_text: "Letters On Liquors "
footer_text: Copyright 2020 Lily-Rose Hill
header_feature_image: ../uploads/photo-1508253730651-e5ace80a7025.jpeg
bannerheight: 20vmax
logo: ../uploads/screenshot-2020-10-08-at-14.37.58.png
favicon: ../uploads/screenshot-2020-10-08-at-14.37.58.png
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About The Author
    siteurl: /aboutme
